 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ingredientes", type: :request do
  # Ingrediente. As you add validations to Ingrediente, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Ingrediente.create! valid_attributes
      get ingredientes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ingrediente = Ingrediente.create! valid_attributes
      get ingrediente_url(ingrediente)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ingrediente_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      ingrediente = Ingrediente.create! valid_attributes
      get edit_ingrediente_url(ingrediente)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Ingrediente" do
        expect {
          post ingredientes_url, params: { ingrediente: valid_attributes }
        }.to change(Ingrediente, :count).by(1)
      end

      it "redirects to the created ingrediente" do
        post ingredientes_url, params: { ingrediente: valid_attributes }
        expect(response).to redirect_to(ingrediente_url(Ingrediente.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Ingrediente" do
        expect {
          post ingredientes_url, params: { ingrediente: invalid_attributes }
        }.to change(Ingrediente, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post ingredientes_url, params: { ingrediente: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ingrediente" do
        ingrediente = Ingrediente.create! valid_attributes
        patch ingrediente_url(ingrediente), params: { ingrediente: new_attributes }
        ingrediente.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ingrediente" do
        ingrediente = Ingrediente.create! valid_attributes
        patch ingrediente_url(ingrediente), params: { ingrediente: new_attributes }
        ingrediente.reload
        expect(response).to redirect_to(ingrediente_url(ingrediente))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        ingrediente = Ingrediente.create! valid_attributes
        patch ingrediente_url(ingrediente), params: { ingrediente: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ingrediente" do
      ingrediente = Ingrediente.create! valid_attributes
      expect {
        delete ingrediente_url(ingrediente)
      }.to change(Ingrediente, :count).by(-1)
    end

    it "redirects to the ingredientes list" do
      ingrediente = Ingrediente.create! valid_attributes
      delete ingrediente_url(ingrediente)
      expect(response).to redirect_to(ingredientes_url)
    end
  end
end
