 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/resultados", type: :request do
  # Resultado. As you add validations to Resultado, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Resultado.create! valid_attributes
      get resultados_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      resultado = Resultado.create! valid_attributes
      get resultado_url(resultado)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_resultado_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      resultado = Resultado.create! valid_attributes
      get edit_resultado_url(resultado)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Resultado" do
        expect {
          post resultados_url, params: { resultado: valid_attributes }
        }.to change(Resultado, :count).by(1)
      end

      it "redirects to the created resultado" do
        post resultados_url, params: { resultado: valid_attributes }
        expect(response).to redirect_to(resultado_url(Resultado.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Resultado" do
        expect {
          post resultados_url, params: { resultado: invalid_attributes }
        }.to change(Resultado, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post resultados_url, params: { resultado: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested resultado" do
        resultado = Resultado.create! valid_attributes
        patch resultado_url(resultado), params: { resultado: new_attributes }
        resultado.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the resultado" do
        resultado = Resultado.create! valid_attributes
        patch resultado_url(resultado), params: { resultado: new_attributes }
        resultado.reload
        expect(response).to redirect_to(resultado_url(resultado))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        resultado = Resultado.create! valid_attributes
        patch resultado_url(resultado), params: { resultado: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested resultado" do
      resultado = Resultado.create! valid_attributes
      expect {
        delete resultado_url(resultado)
      }.to change(Resultado, :count).by(-1)
    end

    it "redirects to the resultados list" do
      resultado = Resultado.create! valid_attributes
      delete resultado_url(resultado)
      expect(response).to redirect_to(resultados_url)
    end
  end
end
